addSbtPlugin("org.scala-js"        % "sbt-scalajs"              % "1.21.0")
addSbtPlugin("org.portable-scala"  % "sbt-scalajs-crossproject" % "1.0.0")
addSbtPlugin("ch.epfl.scala"       % "sbt-scalafix"             % "0.9.31")
addSbtPlugin("com.github.reibitto" % "sbt-welcome"              % "0.2.2")
addSbtPlugin("org.scalameta"       % "sbt-scalafmt"             % "2.4.6")
addSbtPlugin("com.jsuereth"        % "sbt-pgp"                  % "1.1.0")
addSbtPlugin("com.eed3si9n"        % "sbt-salad-days"           % "0.2.0")
